# 因为我们Runner执行器设置为docker, 所以这里需要指定docker的版本
image: docker:stable
# 定义三个阶段
stages:
  - compile
# 定义个变量, 指定maven下载的jar包存放的位置
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
# 第一阶段
compile:
  # 打包用到了maven, 所有需要拉取maven镜像, 这是我自己构建的阿里云maven私服的maven镜像
  image: docker.io/gradle
  # 指定阶段
  stage: compile
  # 运行脚本, 使用变量时要用到 $ 符号
  script:
    - export GRADLE_USER_HOME=/usr/local/repos/gradle
    - gradle clean build
  # 只作用在master分支
  only:
    - master
  # 创建runner时指定的tag
  tags:
    - my-tag
  # 编译后有产物,所以要指定下过期时间和路径, 以供于其他阶段使用
  artifacts:
    expire_in: 1 days
    paths:
      - target/*.jar
      - editor-service/front-service/build/libs/*.jar